# Generated by Django 5.1.2 on 2024-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
