# Generated by Django 5.1.2 on 2024-11-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('1_star', '★☆☆☆☆'), ('2_star', '★★☆☆☆'), ('3_star', '★★★☆☆'), ('4_star', '★★★★☆'), ('5_star', '★★★★★')], default=None),
        ),
    ]
